version: '3.8'
services:
  dev-db:
    image: postgres:13
    container_name: dev-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rainbow
    networks:
      - rainbow

  redis:
    image: 'redis:latest'
    container_name: redis-dev
    ports:
      - '6379:6379'
    networks:
      - rainbow
networks:
  rainbow:
